spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://10.36.101.11:3306/happy_tire?serverTimezone=Asia/Shanghai
    password: 6kjCqjaY

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #输出SQL日志

server:
  port: 8080
